
package com.sap.xi.sd_sls;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalesOrderBulkRequest_In", targetNamespace = "http://sap.com/xi/SD-SLS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.sap.xi.sapglobal20.global.ObjectFactory.class,
    com.sap.xi.sd.ObjectFactory.class,
    com.sap.xi.sd.global2.ObjectFactory.class,
    com.sap.xi.sd_sls.ObjectFactory.class
})
public interface SalesOrderBulkRequestIn {


    /**
     * 
     * @param salesOrderBulkRequest
     */
    @WebMethod(operationName = "SalesOrderBulkRequest_In", action = "http://sap.com/xi/SD-SLS/SalesOrderBulkRequest_In/SalesOrderBulkRequest_InRequest")
    @Oneway
    public void salesOrderBulkRequestIn(
        @WebParam(name = "SalesOrderBulkRequest", targetNamespace = "http://sap.com/xi/SD-SLS", partName = "SalesOrderBulkRequest")
        SalesOrderBulkMessage salesOrderBulkRequest);

}
