
package com.sap.xi.sd_sls;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "service", targetNamespace = "http://sap.com/xi/SD-SLS", wsdlLocation = "classpath:SALESORDERBULKREQUEST_IN4.wsdl")
public class Service
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://sap.com/xi/SD-SLS", "service");

    static {
        SERVICE_WSDL_LOCATION = com.sap.xi.sd_sls.Service.class.getResource("classpath:SALESORDERBULKREQUEST_IN4.wsdl");
        WebServiceException e = null;
        if (SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'classpath:SALESORDERBULKREQUEST_IN4.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SERVICE_EXCEPTION = e;
    }

    public Service() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalesOrderBulkRequestIn
     */
    @WebEndpoint(name = "binding")
    public SalesOrderBulkRequestIn getBinding() {
        return super.getPort(new QName("http://sap.com/xi/SD-SLS", "binding"), SalesOrderBulkRequestIn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalesOrderBulkRequestIn
     */
    @WebEndpoint(name = "binding")
    public SalesOrderBulkRequestIn getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://sap.com/xi/SD-SLS", "binding"), SalesOrderBulkRequestIn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
