
package jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Mon Aug 27 15:23:08 IST 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "printMessage1Response", namespace = "http://DefaultNamespace")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "printMessage1Response", namespace = "http://DefaultNamespace")

public class PrintMessageResponse {

    @XmlElement(name = "return")
    private javax.ws.rs.core.Response _return;

    public javax.ws.rs.core.Response getReturn() {
        return this._return;
    }

    public void setReturn(javax.ws.rs.core.Response new_return)  {
        this._return = new_return;
    }

}

