package com.sap.xi.edi.supplier;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-09-25T13:01:20.868+05:30
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/EDI/Supplier", name = "OrderRequest_In")
@XmlSeeAlso({com.sap.xi.sapglobal.global.ObjectFactory.class, com.sap.xi.edi.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderRequestIn {

    @WebMethod(operationName = "OrderRequest_In", action = "http://sap.com/xi/EDI/Supplier/OrderRequest_In/OrderRequest_InRequest")
    @Oneway
    public void orderRequestIn(

        @WebParam(partName = "OrderRequest", name = "OrderRequest", targetNamespace = "http://sap.com/xi/EDI")
        com.sap.xi.edi.SalesOrderMessage orderRequest
    );
}
