
package com.sap.xi.edi.supplier;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-09-25T13:01:20.843+05:30
 * Generated source version: 3.3.3
 *
 */
public final class OrderRequestIn_Binding_Client {

    private static final QName SERVICE_NAME = new QName("http://sap.com/xi/EDI/Supplier", "service");

    private OrderRequestIn_Binding_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Service ss = new Service(wsdlURL, SERVICE_NAME);
        OrderRequestIn port = ss.getBinding();

        {
        System.out.println("Invoking orderRequestIn...");
        com.sap.xi.edi.SalesOrderMessage _orderRequestIn_orderRequest = null;
        port.orderRequestIn(_orderRequestIn_orderRequest);


        }

        System.exit(0);
    }

}
