package com.sap.xi.edi.supplier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-09-25T13:01:20.883+05:30
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "service",
                  wsdlLocation = "ORDERREQUEST_IN.wsdl",
                  targetNamespace = "http://sap.com/xi/EDI/Supplier")
public class Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sap.com/xi/EDI/Supplier", "service");
    public final static QName BindingSoap12 = new QName("http://sap.com/xi/EDI/Supplier", "binding_soap12");
    public final static QName Binding = new QName("http://sap.com/xi/EDI/Supplier", "binding");
    static {
        URL url = null;
        try {
            System.out.println("---------------"+Service.class.getResource("../../../../../ORDERREQUEST_IN.wsdl").getFile());
            //url = new URL("file:ORDERREQUEST_IN.wsdl");
            url = new URL(Service.class.getResource("../../../../../ORDERREQUEST_IN.wsdl").getFile());
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:ORDERREQUEST_IN.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OrderRequestIn
     */
    @WebEndpoint(name = "binding_soap12")
    public OrderRequestIn getBindingSoap12() {
        return super.getPort(BindingSoap12, OrderRequestIn.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderRequestIn
     */
    @WebEndpoint(name = "binding_soap12")
    public OrderRequestIn getBindingSoap12(WebServiceFeature... features) {
        return super.getPort(BindingSoap12, OrderRequestIn.class, features);
    }


    /**
     *
     * @return
     *     returns OrderRequestIn
     */
    @WebEndpoint(name = "binding")
    public OrderRequestIn getBinding() {
        return super.getPort(Binding, OrderRequestIn.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderRequestIn
     */
    @WebEndpoint(name = "binding")
    public OrderRequestIn getBinding(WebServiceFeature... features) {
        return super.getPort(Binding, OrderRequestIn.class, features);
    }

}
